---
#tasks file for python

- name: Installing Python3
  apt:
    name: python3
    state: latest
    update_cache: yes

- name: Installing pip3
  apt:
    name: python3-pip
    state: latest
    update_cache: yes

- name: Use pip3 as default pip
  command: update-alternative --install /usr/bin/pip pip /usr/bin/pip3 10


- name: Use Python3 as default Python
  command: update-alternatives --install /usr/bin/python python /usr/bin/python3 10 
